alts = int(input("How many accounts do you have (only whole numbers accepted) "))
coins = int(input("How many coins do you have so far (only accepts whole numbers) "))
coins_per_day = int(input("How many coins will you get per day (only accepts whole numbers) "))
days = int(input("How many days will you get that many coins per day for "))

print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("you will get")
print((alts*coins_per_day*days)+coins)
print("coins in this time")
